#!/usr/bin/env bash

# File commands
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias ls='ls -a'
alias dush='du -sh * | sort -hr'
alias wget='wget --hsts-file=$XDG_DATA_HOME/wget-hsts'

# Editors
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'

# Command shortcuts
alias hist='history | grep'
alias srczsh='source $XDG_CONFIG_HOME/zsh/.zshrc; source $XDG_CONFIG_HOME/zsh/.zshenv'
alias fetch='uwufetch'
alias golden='echo 0.61803398875'

# Mac commands
alias icloud='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs'

# Other apps
alias adb='HOME="$XDG_DATA_HOME"/android adb' # adds xdg path

# TMUX
alias tn='tmux new-session -s'
alias tl='tmux list-sessions'
alias ta='tmux attach-session'
